In [1]:
import numpy as np

from src import visualize_n_points

## Theory:

$$
\begin{bmatrix}
M(\mathbf{q}) & J^T(\mathbf{q}) & \mathbf{I} \\
J(\mathbf{q}) & \mathbf{0} & \mathbf{0} \\
\mathbf{I} & \mathbf{0} & \mathbf{0}
\end{bmatrix}
\begin{bmatrix}
\mathbf{\ddot{q}} \\
\mathbf{\lambda} \\
-\mathbf{u}
\end{bmatrix}
= 
\begin{bmatrix}
-h(\mathbf{q}, \mathbf{\dot{q}}) \\
\dot{J}(\mathbf{q}) \mathbf{\dot{q}} \\
-\mathbf{\ddot{q}}^d - K_D \mathbf{\tilde{\dot{q}} - K_D \mathbf{\tilde{q}}
\end{bmatrix}
$$

where, $h(\mathbf{q}, \mathbf{\dot{q}}) = C(\mathbf{q}, \mathbf{\dot{q}}) \mathbf{\dot{q}} + g(\mathbf{q})$

In [5]:
L = 1
M = 1
G = 10


def jac_constraint(q: np.ndarray) -> np.ndarray:
    x_1, y_1, x_2, y_2 = q
    return np.array(
        [
            [2 * x_1, 2 * y_1, 0, 0],
            [2 * (x_2 - x_1), 2 * (y_2 - y_1), 2 * (x_1 - x_2), 2 * (y_1 - y_2)],
        ]
    )


def dot_jac_constraint(_: np.ndarray, dot_q: np.ndarray) -> np.ndarray:
    dot_x_1, dot_y_1, dot_x_2, dot_y_2 = dot_q
    return np.array(
        [
            [2 * dot_x_1, 2 * dot_y_1, 0, 0],
            [2 * (dot_x_2 - dot_x_1), 2 * (dot_y_2 - dot_y_1), 2 * (dot_x_1 - dot_x_2), 2 * (dot_y_1 - dot_y_2)],
        ]
    )


def h_val(_: np.ndarray, __: np.ndarray) -> np.ndarray:
    return np.array([0, M * G, 0, M * G])


def mass_matrix(_: np.ndarray) -> np.ndarray:
    return M * np.eye(4)

In [7]:
def full_matrix(q: np.ndarray) -> np.ndarray:
    res = np.zeros((10, 10))

    res[:4,:4] = mass_matrix(q)
    res[:4,4:6] = jac_constraint(q).T
    res[4:6, :4] = jac_constraint(q)
    res[:4, 6:] = np.eye(4)
    res[6:, :4] = np.eye(4)

    return res

In [12]:
full = full_matrix(np.array([1, 0, 2, 0]))

print(full) # A singular case!

[[ 1.  0.  0.  0.  2.  2.  1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0. -2.  0.  0.  1.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  1.]
 [ 2.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 2.  0. -2.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]]
